version: '3.1'

services:
  database:
    image: mongo:4.4.6
    hostname: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: users
    ports:
      - 27017:27017
  backend:
    build: ./backend
    environment:
      MONGO_INITDB_ROOT_PASSWORD: pwd
    ports:
      - 5000:5000
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend